### ISSUE TITLE
Error on macos

### ISSUE THREAD

**Issue by deflexable** [NoobToolzz/Bloody-Proxy-Scraper#2]
getting this error on macos: `macos@Anthony Bloody-proxy-Scraper % pip install -r requirements.txt  
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: requests in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (2.31.0)
Collecting pystyle (from -r requirements.txt (line 2))
  Using cached pystyle-2.9-py3-none-any.whl.metadata (343 bytes)
Collecting datetime (from -r requirements.txt (line 3))
  Using cached DateTime-5.5-py3-none-any.whl.metadata (33 kB)
Collecting console (from -r requirements.txt (line 4))
  Using cached console-0.9907-py2.py3-none-any.whl.metadata (17 kB)
ERROR: Could not find a version that satisfies the requirement AutoUpdate (from versions: none)
ERROR: No matching distribution found for AutoUpdate`

**Comment by NoobToolzz** [comment]
The `AutoUpdate` package no longer exists. I may remove the module out of the files soon.
